services:
  web-apps:
    build: ./apps
    container_name: web-apps
    image: rifqidev/image-rifqi
    ports:
      - 5000:3000
    volumes:
      - web-app-data:/app/public/images

volumes:
  web-app-data:
